FULL_SCREEN_BOOK_READER_AD_UNIT="abc"
OPEN_BOOK_GRID_AD_UNIT="abc"
OPEN_BOOK_LIST_AD_UNIT="abc"
READER_SCREEN_AD_UNIT="abc"
PRODUCT_ID="abc"
keyAlias="wxngame"
keyPassword="wxn230124"
storeFile=file("./app/android-key.jks")
storePassword="wxn230124"
enableV1Signing=true
enableV2Signing=true
enableAd=false